# Generated by Django 4.1.3 on 2022-11-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profile_avatar_alter_profile_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_pics/avatar_default.JPG', upload_to='profile_pics'),
        ),
    ]
