# Generated by Django 4.1.3 on 2022-11-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_pics/avatar_default.jpg', upload_to='profile_pics'),
        ),
    ]
